[build]
base = "./"
publish = "build/"
command = "npm run build"

[build.environment]
  REACT_APP_BASE_URL = "/api"

# https://docs.netlify.com/routing/redirects/
# redirects for API calls
[[redirects]]
  from = "/api/actioncards/latest/"
  to = "http://159.89.54.69:8000/actioncards/latest/"
  status = 200

[[redirects]]
  from = "/api/actioncards"
  to = "http://159.89.54.69:8000/actioncards/"
  status = 200

[[redirects]]
  from = "/api/surveyresponses/"
  to = "http://159.89.54.69:8000/surveyresponses/"
  status = 200

[[redirects]]
  from = "/api/actions/"
  to = "http://159.89.54.69:8000/actions/"
  status = 200

[[redirects]]
  from = "/api/surveyresponses/user/"
  to = "http://159.89.54.69:8000/surveyresponses/user/"
  status = 200

[[redirects]]
  from = "/api/token/"
  to = "http://159.89.54.69:8000/token/"
  status = 200

[[redirects]]
  from = "/api/rest-auth/logout/"
  to = "http://159.89.54.69:8000/rest-auth/logout/"
  status = 200

[[redirects]]
  from = "/api/user/"
  to = "http://159.89.54.69:8000/user/"
  status = 200

[[redirects]]
  # fallback redirect for all other pages
  # to drive it back to the SPA index.html
  # page that can do client-side routing
  from = "/*"
  to = "/index.html"
  status = 200
