[build]
base = "./"
publish = "build/"
command = "npm run build"

[build.environment]
  REACT_APP_BASE_URL = "/api"

# https://docs.netlify.com/routing/redirects/
[[redirects]]
  from = "/api/actioncards/latest/"
  to = "http://159.89.54.69:8000/actioncards/latest/"
  status = 200

[[redirects]]
  from = "/api/actioncards"
  to = "http://159.89.54.69:8000/actioncards"
  status = 200
