//const baseUrl: string = 'https://server-dot-actions-server-260415.appspot.com';
const baseUrl: string = 'http://localhost:8000';
export const ACTION_CARD_URL=`${baseUrl}/actioncards/`;
export const LATEST_ACTION_CARD_URL=`${baseUrl}/actioncards/latest/`
export const ACTION_URL=`${baseUrl}/actions/`;
export const SURVEY_RESPONSE_URL=`${baseUrl}/surveyresponses/`;
export const USER_SURVEY_RESPONSE_URL=`${baseUrl}/surveyresponses/user/`;
export const SIGN_IN_URL=`${baseUrl}/rest-auth/login/`;
export const SIGN_OUT_URL=`${baseUrl}/rest-auth/louout/`;
export const CURRENT_USER_URL=`${baseUrl}/user/`;