name: netlify-prod
# production deploys only happens on pushes to the master branch
on:
  push:
    branches:
      - master

jobs:
  netlify-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # first, let's test the site locally
      - name: Cypress run against local site
        uses: cypress-io/github-action@v1
        with:
          start: npm run react:start
          wait-on: 'http://localhost:3000'

      # if the tests pass, let's build production site
      - name: Build site
        run: npm run build
        env:
          # unset CI environment variable so warnings are not treated as errors
          CI:
          # point API calls to "/api" that will later be redirected
          # to the remote API host
          REACT_APP_BASE_URL: '/api'
          REACT_APP_COMMIT_SHA: GITHUB_SHA

      - run: npm install netlify-cli
      - name: Deploy to Netlify prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        # when deploying show the output from Netlify
        # and redirect its results into a JSON file
        run: npx netlify deploy --dir build --json | tee deploy.json

      - name: Run Cypress tests against draft deploy
        run: node ./scripts/test-prod-site.js

      - name: Make it live
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npx netlify deploy --prod --dir build --json | tee deploy.json

      - name: Run Cypress tests against prod deploy
        run: node ./scripts/test-prod-site.js
