name: netlify
on: [pull_request]
jobs:
  netlify-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        uses: cypress-io/github-action@v1
        with:
          # just perform install
          runTests: false
      - run: npx print-env GITHUB
      - name: Build site
        run: REACT_APP_COMMIT_SHA=$GITHUB_SHA npm run build
        env:
          # unset CI environment variable so warnings are not treated as errors
          CI:
          # point API calls to "/api" that will later be redirected
          # to the remote API host
          REACT_APP_BASE_URL: '/api'
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        # when deploying show the output from Netlify
        # and redirect its results into a JSON file
        run: |
          npm install netlify-cli
          npx netlify deploy --dir build --json | tee deploy.json

      - name: Run Cypress tests against draft deploy
        run: node ./scripts/test-draft-site.js

      # only runs read-only tests without stubbing
      - name: Run prod tests against draft deploy
        run: node ./scripts/test-prod-site.js
